# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lenovo/Desktop/PS918106840727/PS918106840727.srcs/sources_1/bd/PS918106840727/ip/PS918106840727_processing_system7_0_1/PS918106840727_processing_system7_0_1.xci
# IP: The module: 'PS918106840727_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lenovo/Desktop/PS918106840727/PS918106840727.srcs/sources_1/bd/PS918106840727/ip/PS918106840727_processing_system7_0_1/PS918106840727_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS918106840727_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/lenovo/Desktop/PS918106840727/PS918106840727.srcs/sources_1/bd/PS918106840727/ip/PS918106840727_processing_system7_0_1/PS918106840727_processing_system7_0_1.xci
# IP: The module: 'PS918106840727_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lenovo/Desktop/PS918106840727/PS918106840727.srcs/sources_1/bd/PS918106840727/ip/PS918106840727_processing_system7_0_1/PS918106840727_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS918106840727_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
