# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/hw_des_II/item3/item3.srcs/sources_1/bd/item3/ip/item3_processing_system7_0_0/item3_processing_system7_0_0.xci
# IP: The module: 'item3_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/hw_des_II/item3/item3.srcs/sources_1/bd/item3/ip/item3_processing_system7_0_0/item3_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'item3_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/hw_des_II/item3/item3.srcs/sources_1/bd/item3/ip/item3_processing_system7_0_0/item3_processing_system7_0_0.xci
# IP: The module: 'item3_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/hw_des_II/item3/item3.srcs/sources_1/bd/item3/ip/item3_processing_system7_0_0/item3_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'item3_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
