# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PS918106840727.xdc

# Block Designs: bd/PS918106840727/PS918106840727.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS918106840727 || ORIG_REF_NAME==PS918106840727} -quiet] -quiet

# IP: bd/PS918106840727/ip/PS918106840727_processing_system7_0_1/PS918106840727_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS918106840727_processing_system7_0_1 || ORIG_REF_NAME==PS918106840727_processing_system7_0_1} -quiet] -quiet

# XDC: bd/PS918106840727/PS918106840727_ooc.xdc
