# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/item3.xdc

# Block Designs: bd/item3/item3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==item3 || ORIG_REF_NAME==item3} -quiet] -quiet

# IP: bd/item3/ip/item3_processing_system7_0_0/item3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==item3_processing_system7_0_0 || ORIG_REF_NAME==item3_processing_system7_0_0} -quiet] -quiet

# XDC: bd/item3/item3_ooc.xdc
